### PR TITLE
fixed a feature, formatted the script a bit, and some more stuff i forgot

### PR DESCRIPTION
**Pull request by ActualMasterOogway**
this time i actually followed the [conventional commits whatever](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by ActualMasterOogway** [comment]
thanks mstudio for making this conflict ❤️ 🫶

**Comment by notpoiu** [comment]
sorry bro 😭 i think a lil too late

**Comment by notpoiu** [comment]
fuck i mean homie

**Comment by ActualMasterOogway** [comment]
> sorry bro 😭 i think a lil too late

YALL WERE TOO LATE!

**Pull request closed without merging**
